@startuml

class Main {
    +main() : void
}

class PesananMakanan {
    +PesananMakanan() : void
    +TotalHarga(harga: int) : void
}

class PesananMinuman {
    +PesananMinuman() : void
    +TotalHarga(harga: int) : void
}

Main "1" --> "1" PesananMakanan : create
Main "1" --> "1" PesananMinuman : create
PesananMakanan "1" --> "1" TotalHarga : call
PesananMinuman "1" --> "1" TotalHarga : call

@enduml